[package]
name = "jolt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
hdrhistogram = "7.5.4"
humantime = "2.2.0"
reqwest = "0.12.22"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
